### ISSUE TITLE
don't use absolute dependency versions

### ISSUE THREAD

**Issue by felschr** [StaticJsCMS/gatsby-plugin-static-cms#28]
Please don't use absolute versions in `dependencies`.

In my case this caused 2 versions of `html-webpack-plugin` (`5.5.0` & `5.5.3`) to be installed in my npm workspace which in turn caused this error: https://github.com/jharris4/html-webpack-tags-plugin/pull/88

**Comment by KaneFreeman** [comment]
This is resolved with version `3.0.0`.
